Fix ARM compatibility #22
uhafner/warnings-ng-plugin-devenv pull request #24
Opened 2024-06-02 13:00 UTC by Derpzz

This PR addresses issue #22 by updating all Docker images to the latest versions that support ARM. While I was able to run this successfully on my ARM M1 MacBook, I do not have a reference of the prior state. Therefore, please test extensively before merging.

2024-06-03 09:07 UTC, uhafner requested changes
I think it makes sense to separate the controller changes from the agent changes...

2024-06-03 09:07 UTC, uhafner commented on docker/images/java-agent/Dockerfile
> +FROM eclipse-temurin:22-alpine
This Java agent is supposed to run Java 17, does it not work on your architecture?

2024-06-03 09:07 UTC, uhafner commented on docker/images/java-11-agent/Dockerfile
> +FROM eclipse-temurin:22-alpine
This Java agent is supposed to run Java 11, does it not work on your architecture?

2024-06-03 09:07 UTC, uhafner commented on docker/images/java-agent/Dockerfile
> +FROM eclipse-temurin:22-alpine
I think I need to add another agent that runs Java 21

2024-06-08 17:15 UTC, Derpzz commented
I reverted all agent changes. Now this PR only contains the controller version bump. All agent changes will be in a separate PR.

2024-06-16 20:42 UTC, uhafner approved these changes

2024-06-16 20:42 UTC, merged